### ISSUE TITLE
SyntaxError: invalid syntax error on fresh install client 

### ISSUE THREAD

**Issue by asmeureanu** [rcoenmans/vsts-client#1]
Hi,

Freshly installed with pip I am getting this syntax error when i import the library 
```
Traceback (most recent call last):
  File "vsts.py", line 1, in <module>
    from vstsclient.vstsclient import VstsClient
  File "/usr/local/lib/python2.7/dist-packages/vstsclient/vstsclient.py", line 126
    def change_workitem_type(self, workitem_id: int, workitem_type_name):
                                                                          ^
SyntaxError: invalid syntax
```

```
from vstsclient.vstsclient import VstsClient
```

**Comment by rcoenmans** [comment]
Hi,

Would you be able switch to python 3.x? I'll look into making it 2.x compatible.

**Comment by rcoenmans** [comment]
At this point in time we do not have any plans to make this library compatible with Python 2.x.
